### ISSUE TITLE
✨ 优化registry API切换设置

### ISSUE THREAD

**Issue by Lzzzs** [depazer/depazer#14]
## 优化API设置

写一个AutoComplete组件([类似这样](https://arco.design/vue/component/auto-complete))

支持自动补全[`https://registry.npmmirror.com/`, `https://registry.npmjs.cf/`]

![Image](https://user-images.githubusercontent.com/86412303/258694540-dcf62531-c9e9-4908-bcb7-f20a960f82b6.png)

**Comment by Jon-a-than** [comment]
可能有自己搭建的npm仓库，可以填入后加个验证？
